apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/appu-learn/demo-talk
    context: app
deploy:
  kubectl:
    manifests:
      - k8s-*

profiles:
  - name: gcb
    build:
      tagPolicy:
        dateTime: {}
      googleCloudBuild:
        projectId: appu-learn
